# Generated by Django 3.2.7 on 2021-09-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolair', '0004_alter_image_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.PositiveBigIntegerField(blank=True, default=50, help_text='Account balance of credits available to the user', verbose_name='Credits'),
        ),
    ]
